from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.units import inch
from io import BytesIO
from datetime import datetime
from typing import Dict, Any, List
from backend.models.user import User
from backend.models.soil import SoilReport
from backend.models.iot import IoTData
from backend.models.crop import CropResponse

async def generate_farm_report(data: Dict[str, Any], report_type: str) -> bytes:
    """Generate PDF report for farm data"""

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()

    # Title
    title = Paragraph(f"<b>AI Rythu Mitra - Farm Report</b>", styles['Title'])
    elements.append(title)
    elements.append(Spacer(1, 0.3 * inch))

    # Date
    date_text = Paragraph(f"Generated on: {datetime.now().strftime('%B %d, %Y')}", styles['Normal'])
    elements.append(date_text)
    elements.append(Spacer(1, 0.2 * inch))

    # Farmer Information
    if 'user' in data and isinstance(data['user'], User):
        user: User = data['user']
        farmer_info = [
            ['Farmer Name:', user.name or 'N/A'],
            ['Location:', user.farm_location or 'N/A'],
            ['Farm Size:', f"{user.farm_size or 'N/A'} acres"],
            ['Contact:', user.phone or 'N/A']
        ]

        table = Table(farmer_info, colWidths=[2 * inch, 4 * inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))

        elements.append(table)
        elements.append(Spacer(1, 0.3 * inch))

    # Soil Reports Summary
    if 'soil_reports' in data and data['soil_reports']:
        elements.append(Paragraph("<b>Recent Soil Analysis</b>", styles['Heading2']))
        elements.append(Spacer(1, 0.1 * inch))

        for report in data['soil_reports']:
            if isinstance(report, SoilReport):
                text = f"<b>Report ID:</b> {report.id}<br/>"
                text += f"<b>Date:</b> {report.created_at.strftime('%B %d, %Y')} <br/>"
                text += f"<b>Analysis:</b> {report.analysis.get('analysis', 'Pending')}<br/>"

                elements.append(Paragraph(text, styles['Normal']))
                elements.append(Spacer(1, 0.1 * inch))

    # IoT Data Summary
    if 'iot_data' in data and data['iot_data']:
        elements.append(Spacer(1, 0.2 * inch))
        elements.append(Paragraph("<b>Latest Sensor Readings</b>", styles['Heading2']))
        elements.append(Spacer(1, 0.1 * inch))

        iot_table_data = [['Timestamp', 'Moisture %', 'Temperature °C', 'Humidity %']]

        for reading in data['iot_data']:
            if isinstance(reading, IoTData):
                iot_table_data.append([
                    reading.timestamp.strftime('%Y-%m-%d %H:%M:%S'),
                    f"{reading.moisture:.1f}",
                    f"{reading.temperature:.1f}",
                    f"{reading.humidity:.1f}"
                ])

        if len(iot_table_data) > 1:
            iot_table = Table(iot_table_data, colWidths=[2.5 * inch, 1.2 * inch, 1.5 * inch, 1.3 * inch])
            iot_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))

            elements.append(iot_table)

    # Crop Recommendations
    if 'crop_recommendations' in data and data['crop_recommendations']:
        elements.append(PageBreak())
        elements.append(Paragraph("<b>AI Crop Recommendations</b>", styles['Heading2']))
        elements.append(Spacer(1, 0.1 * inch))

        for rec in data['crop_recommendations']:
            if isinstance(rec, CropResponse):
                text = f"<b>{rec.name}</b><br/>"
                text += f"Suitability: {rec.suitability_score}/100<br/>"
                text += f"Expected Yield: {rec.expected_yield}<br/>"
                text += f"Duration: {rec.growth_duration}<br/>"
                elements.append(Paragraph(text, styles['Normal']))
                elements.append(Spacer(1, 0.15 * inch))

    # Footer
    elements.append(Spacer(1, 0.5 * inch))
    footer = Paragraph(
        "<i>This report is generated by AI Rythu Mitra for agricultural guidance purposes.</i>",
        styles['Normal']
    )
    elements.append(footer)

    # Build PDF
    doc.build(elements)

    pdf_content = buffer.getvalue()
    buffer.close()

    return pdf_content
